In [5]:
import pandas as pd
import mysql.connector

In [6]:
dfbus1=pd.read_csv("kerala_bus.csv")
dfbus2=pd.read_csv("andhra_bus.csv")
dfbus3=pd.read_csv("assam_bus.csv")
dfbus4=pd.read_csv("Goa_bus.csv")
dfbus5=pd.read_csv("haryana_bus.csv")
dfbus6=pd.read_csv("rajasthan_bus.csv")
dfbus7=pd.read_csv("south_bengal_bus.csv")
dfbus8=pd.read_csv("telungana_bus.csv")
dfbus9=pd.read_csv("UTTAR_PRADESH_bus.csv")
dfbus10=pd.read_csv("west_bengel_bus.csv")
dfbus=pd.concat([dfbus1,dfbus2,dfbus3,dfbus4,dfbus5,dfbus6,dfbus7,dfbus8,dfbus9,dfbus10])
dfbus

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_name,Route_link,Unnamed: 0
0,Kyros Connect,Bharat Benz A/C Semi Sleeper (2+2),23:00,09:00,10h 00m,599.0,15 Seats available,4.0\n339,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,NaN
1,P K Travels,A/C Seater / Sleeper (2+1),21:30,06:00,08h 30m,750.0,31 Seats available,4.0\n54,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,NaN
2,MMK Travels,A/C Seater / Sleeper (2+1),22:30,07:30,09h 00m,750.0,11 Seats available,4.6\n555,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,NaN
3,AdNS Transports,VE A/C Sleeper (2+1),22:45,07:30,08h 45m,878.0,9 Seats available,4.0\n292,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,NaN
4,SKS Tours & Travels,A/C Sleeper (2+1),21:15,05:45,08h 30m,849.0,13 Seats available,4.3\n90,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
124,WBTC (CTC) Habra-Midnapur - 194|05:55,Non AC Seater (2+3),05:55,10:15,04h 20m,138.0,39 Seats available,4.5\n26,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...,NaN
125,SBSTC-HABRA - MIDNAPUR - 06:20 (MID DEPOT) - 1398,Non AC Seater (2+3),06:20,00:00,17h 40m,143.0,51 Seats available,4.1\n23,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...,NaN
126,SBSTC-BONGAON - ASANSOL - VIA - BARASAT - 05:0...,Non AC Seater (2+3),06:00,11:00,05h 00m,180.0,49 Seats available,3.2\n22,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...,NaN
127,SBSTC-HABRA - DURGAPUR - VIA - BARASAT - 07:00...,Non AC Seater (2+3),07:00,12:00,05h 00m,180.0,45 Seats available,4.2\n55,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...,NaN
128,WBTC (CTC) Habra - Barasat - Durgapur - Asanso...,Non AC Seater (2+3),05:05,09:00,03h 55m,165.0,43 Seats available,3.6\n36,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...,NaN

In [7]:
dfbus.isna().sum()

Bus_name             35
Bus_type             37
Start_time           35
End_time             35
Total_duration       35
Price                35
Seats_Available      35
Ratings              35
Route_name            0
Route_link            0
Unnamed: 0         3160
dtype: int64

In [8]:
dfbus.drop(columns=["Unnamed: 0"], inplace=True)  # Deletes the "Rating" column
dfbus

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_name,Route_link
0,Kyros Connect,Bharat Benz A/C Semi Sleeper (2+2),23:00,09:00,10h 00m,599.0,15 Seats available,4.0\n339,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
1,P K Travels,A/C Seater / Sleeper (2+1),21:30,06:00,08h 30m,750.0,31 Seats available,4.0\n54,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
2,MMK Travels,A/C Seater / Sleeper (2+1),22:30,07:30,09h 00m,750.0,11 Seats available,4.6\n555,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
3,AdNS Transports,VE A/C Sleeper (2+1),22:45,07:30,08h 45m,878.0,9 Seats available,4.0\n292,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
4,SKS Tours & Travels,A/C Sleeper (2+1),21:15,05:45,08h 30m,849.0,13 Seats available,4.3\n90,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
...,...,...,...,...,...,...,...,...,...,...
124,WBTC (CTC) Habra-Midnapur - 194|05:55,Non AC Seater (2+3),05:55,10:15,04h 20m,138.0,39 Seats available,4.5\n26,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
125,SBSTC-HABRA - MIDNAPUR - 06:20 (MID DEPOT) - 1398,Non AC Seater (2+3),06:20,00:00,17h 40m,143.0,51 Seats available,4.1\n23,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
126,SBSTC-BONGAON - ASANSOL - VIA - BARASAT - 05:0...,Non AC Seater (2+3),06:00,11:00,05h 00m,180.0,49 Seats available,3.2\n22,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
127,SBSTC-HABRA - DURGAPUR - VIA - BARASAT - 07:00...,Non AC Seater (2+3),07:00,12:00,05h 00m,180.0,45 Seats available,4.2\n55,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
128,WBTC (CTC) Habra - Barasat - Durgapur - Asanso...,Non AC Seater (2+3),05:05,09:00,03h 55m,165.0,43 Seats available,3.6\n36,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...

In [9]:
dfbus.dropna(inplace=True)
dfbus

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_name,Route_link
0,Kyros Connect,Bharat Benz A/C Semi Sleeper (2+2),23:00,09:00,10h 00m,599.0,15 Seats available,4.0\n339,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
1,P K Travels,A/C Seater / Sleeper (2+1),21:30,06:00,08h 30m,750.0,31 Seats available,4.0\n54,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
2,MMK Travels,A/C Seater / Sleeper (2+1),22:30,07:30,09h 00m,750.0,11 Seats available,4.6\n555,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
3,AdNS Transports,VE A/C Sleeper (2+1),22:45,07:30,08h 45m,878.0,9 Seats available,4.0\n292,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
4,SKS Tours & Travels,A/C Sleeper (2+1),21:15,05:45,08h 30m,849.0,13 Seats available,4.3\n90,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
...,...,...,...,...,...,...,...,...,...,...
124,WBTC (CTC) Habra-Midnapur - 194|05:55,Non AC Seater (2+3),05:55,10:15,04h 20m,138.0,39 Seats available,4.5\n26,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
125,SBSTC-HABRA - MIDNAPUR - 06:20 (MID DEPOT) - 1398,Non AC Seater (2+3),06:20,00:00,17h 40m,143.0,51 Seats available,4.1\n23,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
126,SBSTC-BONGAON - ASANSOL - VIA - BARASAT - 05:0...,Non AC Seater (2+3),06:00,11:00,05h 00m,180.0,49 Seats available,3.2\n22,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
127,SBSTC-HABRA - DURGAPUR - VIA - BARASAT - 07:00...,Non AC Seater (2+3),07:00,12:00,05h 00m,180.0,45 Seats available,4.2\n55,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
128,WBTC (CTC) Habra - Barasat - Durgapur - Asanso...,Non AC Seater (2+3),05:05,09:00,03h 55m,165.0,43 Seats available,3.6\n36,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...

In [10]:
dfbus.isna().sum()

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_name         0
Route_link         0
dtype: int64

In [11]:
dfbus.shape

(3995, 10)

In [12]:
dfbus['Route_link'].unique

<bound method Series.unique of 0      https://www.redbus.in/bus-tickets/bangalore-to...
1      https://www.redbus.in/bus-tickets/bangalore-to...
2      https://www.redbus.in/bus-tickets/bangalore-to...
3      https://www.redbus.in/bus-tickets/bangalore-to...
4      https://www.redbus.in/bus-tickets/bangalore-to...
                             ...
124    https://www.redbus.in/bus-tickets/habra-to-mid...
125    https://www.redbus.in/bus-tickets/habra-to-mid...
126    https://www.redbus.in/bus-tickets/habra-to-dur...
127    https://www.redbus.in/bus-tickets/habra-to-dur...
128    https://www.redbus.in/bus-tickets/habra-to-dur...
Name: Route_link, Length: 3995, dtype: object>

In [13]:
dfbus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3995 entries, 0 to 128
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bus_name         3995 non-null   object
 1   Bus_type         3995 non-null   object
 2   Start_time       3995 non-null   object
 3   End_time         3995 non-null   object
 4   Total_duration   3995 non-null   object
 5   Price            3995 non-null   float64
 6   Seats_Available  3995 non-null   object
 7   Ratings          3995 non-null   object
 8   Route_name       3995 non-null   object
 9   Route_link       3995 non-null   object
dtypes: float64(1), object(9)
memory usage: 343.3+ KB

In [14]:
dfbus['Start_time']=pd.to_datetime(dfbus['Start_time'],format="%H:%M").dt.strftime("%H:%M")

In [15]:
dfbus['End_time']=pd.to_datetime(dfbus['End_time'],format="%H:%M").dt.strftime('%H:%M')

In [16]:
print(type(dfbus['End_time'][0]))
print(type(dfbus['Start_time'][0]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [17]:
dfbus['Start_time']

0      23:00
1      21:30
2      22:30
3      22:45
4      21:15
       ...
124    05:55
125    06:20
126    06:00
127    07:00
128    05:05
Name: Start_time, Length: 3995, dtype: object

In [18]:
dfbus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3995 entries, 0 to 128
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bus_name         3995 non-null   object
 1   Bus_type         3995 non-null   object
 2   Start_time       3995 non-null   object
 3   End_time         3995 non-null   object
 4   Total_duration   3995 non-null   object
 5   Price            3995 non-null   float64
 6   Seats_Available  3995 non-null   object
 7   Ratings          3995 non-null   object
 8   Route_name       3995 non-null   object
 9   Route_link       3995 non-null   object
dtypes: float64(1), object(9)
memory usage: 472.4+ KB

In [19]:
dfbus['Ratings']

0      4.0\n339
1       4.0\n54
2      4.6\n555
3      4.0\n292
4       4.3\n90
         ...
124     4.5\n26
125     4.1\n23
126     3.2\n22
127     4.2\n55
128     3.6\n36
Name: Ratings, Length: 3995, dtype: object

In [20]:
dfbus['Ratings'] = dfbus['Ratings'].str.split('\n').str[0]

dfbus['Ratings'] = pd.to_numeric(dfbus['Ratings'], errors='coerce')

In [ ]:
dfbus['Ratings']
dfbus.fillna(0, inplace=True)

In [22]:
df = df.applymap(str)

C:\Users\bhara\AppData\Local\Temp\ipykernel_8824\1614842595.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)

In [23]:
dfbus.to_csv("total_bus.csv", index=False)
dfbus

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_name,Route_link
0,Kyros Connect,Bharat Benz A/C Semi Sleeper (2+2),23:00,09:00,10h 00m,599.0,15 Seats available,4.0,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
1,P K Travels,A/C Seater / Sleeper (2+1),21:30,06:00,08h 30m,750.0,31 Seats available,4.0,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
2,MMK Travels,A/C Seater / Sleeper (2+1),22:30,07:30,09h 00m,750.0,11 Seats available,4.6,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
3,AdNS Transports,VE A/C Sleeper (2+1),22:45,07:30,08h 45m,878.0,9 Seats available,4.0,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
4,SKS Tours & Travels,A/C Sleeper (2+1),21:15,05:45,08h 30m,849.0,13 Seats available,4.3,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
...,...,...,...,...,...,...,...,...,...,...
124,WBTC (CTC) Habra-Midnapur - 194|05:55,Non AC Seater (2+3),05:55,10:15,04h 20m,138.0,39 Seats available,4.5,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
125,SBSTC-HABRA - MIDNAPUR - 06:20 (MID DEPOT) - 1398,Non AC Seater (2+3),06:20,00:00,17h 40m,143.0,51 Seats available,4.1,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
126,SBSTC-BONGAON - ASANSOL - VIA - BARASAT - 05:0...,Non AC Seater (2+3),06:00,11:00,05h 00m,180.0,49 Seats available,3.2,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
127,SBSTC-HABRA - DURGAPUR - VIA - BARASAT - 07:00...,Non AC Seater (2+3),07:00,12:00,05h 00m,180.0,45 Seats available,4.2,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
128,WBTC (CTC) Habra - Barasat - Durgapur - Asanso...,Non AC Seater (2+3),05:05,09:00,03h 55m,165.0,43 Seats available,3.6,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...

In [28]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\bhara\appdata\local\programs\python\python312\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [40]:
import pymysql
import pandas as pd

# Database connection
try:
    conn = pymysql.connect(
        host="localhost",
        user="root",
        password="Bharath@0808",  # Replace with your actual MySQL password
        autocommit=True
    )
    print("✅ Connected to MySQL successfully!")

    with conn.cursor() as cursor:
        # Create the database if it doesn't exist
        cursor.execute("CREATE DATABASE IF NOT EXISTS redbus")
        print("✅ Database 'redbus' checked/created.")

except Exception as e:
    print("❌ Error connecting to MySQL:", e)

# Connect to the redbus database
try:
    conn = pymysql.connect(
        host="localhost",
        user="root",
        password="Bharath@0808",
        database="redbus",  # Now connecting to the 'redbus' database
        autocommit=True
    )
    cursor = conn.cursor()

    # Creating a table in redbus database
    create_table_query = """
    CREATE TABLE IF NOT EXISTS bus_data (
        Bus_name VARCHAR(255),
        Bus_type VARCHAR(100),
        Start_time VARCHAR(50),
        End_time VARCHAR(50),
        Total_duration VARCHAR(50),
        Price VARCHAR(50),
        Seats_Available VARCHAR(50),
        Ratings VARCHAR(20),
        Route_name TEXT,
        Route_link TEXT
    )
    """
    cursor.execute(create_table_query)
    print("✅ Table 'bus_data' checked/created.")

    # Load CSV file into DataFrame
    df = pd.read_csv('total_bus.csv')

    # Insert data into MySQL table
    #insert_query ="""INSERT INTO bus_data (Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_name, Route_link)
    #VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    #"""

    # Convert DataFrame to list of tuples
    data = [tuple(x) for x in df.to_records(index=False)]

    # Bulk insert
    cursor.executemany("""INSERT INTO bus_data (Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_name, Route_link)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""", data)
    conn.commit()
    print(f"✅ Successfully inserted {len(df)} records into 'bus_data' table.")

except Exception as e:
    print("❌ Error:", e)

finally:
    # Close connection
    cursor.close()
    conn.close()
    print("✅ Connection closed.")

✅ Connected to MySQL successfully!
✅ Database 'redbus' checked/created.
✅ Table 'bus_data' checked/created.
✅ Successfully inserted 3995 records into 'bus_data' table.
✅ Connection closed.